# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytitle',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=64),
        ),
        migrations.AlterField(
            model_name='producer',
            name='ethical',
            field=models.CharField(choices=[('t', 'Ethical'), ('f', 'Not ethical'), ('u', 'Undefined')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='producertitle',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=64),
        ),
        migrations.AlterField(
            model_name='producttitle',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=64),
        ),
    ]
