# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160318_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(choices=[('vegan', 'vegan'), ('vegeterian', 'vegeterian'), ('fish', 'fish'), ('meat', 'meat'), ('milk', 'milk')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CodeType'),
        ),
    ]
