# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160411_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetype',
            name='title',
        ),
    ]
