# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_codetype_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=64)),
                ('text', models.TextField()),
            ],
        ),
    ]
