# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='text',
            new_name='message',
        ),
    ]
