# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(choices=[('vegan', 'vegan'), ('vegeterian', 'vegeterian'), ('fish', 'fish'), ('meat', 'meat'), ('milk', 'milk'), ('unknown', 'unknown')], max_length=255),
        ),
    ]
