# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160423_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('undefined', 'undefined'), ('manual', 'manual'), ('user', 'user'), ('goodsmatrix.ru', 'goodsmatrix.ru')], default='undefined', max_length=64),
        ),
    ]
