# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=64)),
                ('composition', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.AddField(
            model_name='productcomposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
