
OK = 0
WRONG_CONTENT_TYPE = -2
JSON_EXPECTED = -3
NO_IMAGE = -5
PRODUCT_NOT_FOUND = -7
WRONG_PARAMETERS = -5
WRONG_PARAMETER_VALUE = -11
CATEGORY_NOT_FOUND = -17
PRODUCT_EXISTS = -19
PHOTO_NOT_FOUND = -13
